# Generated by Django 6.0.3 on 2026-03-20 08:34

import diary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "result",
                    models.CharField(
                        choices=[("win", "胜"), ("lose", "负")], max_length=4
                    ),
                ),
                ("clear_count", models.PositiveIntegerField(default=0)),
                ("score", models.IntegerField(default=0)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=diary.models.daily_media_upload_to),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "图片"), ("video", "视频")], max_length=5
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_items",
                        to="diary.dailyrecord",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="dailyrecord",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="unique_daily_record_per_user_per_date"
            ),
        ),
    ]
