# Generated by Django 6.0.3 on 2026-03-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyrecord",
            name="clear_boom_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="clear_in_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model("diary", "DailyRecord").objects.filter(
                clear_count__gt=0, clear_in_count=0
            ).update(clear_in_count=models.F("clear_count")),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
