# Generated by Django 6.0.3 on 2026-03-20 09:04

from django.db import migrations, models


def _forward(apps, schema_editor):
    DailyRecord = apps.get_model("diary", "DailyRecord")
    # 把旧的胜/负迁移成一个最小可用的默认比分（避免历史记录空白）
    DailyRecord.objects.filter(result="win", score_for=0, score_against=0).update(
        score_for=1, score_against=0
    )
    DailyRecord.objects.filter(result="lose", score_for=0, score_against=0).update(
        score_for=0, score_against=1
    )


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_dailyrecord_clear_boom_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyrecord",
            name="opponent_name",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="score_against",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="score_for",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(
            code=_forward,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
