# Generated by Django 6.0.3 on 2026-03-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0003_dailyrecord_opponent_name_dailyrecord_score_against_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyrecord",
            name="clear_count",
        ),
        migrations.RemoveField(
            model_name="dailyrecord",
            name="result",
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="game_type",
            field=models.CharField(
                choices=[("8ball", "黑八"), ("score", "追分")],
                default="8ball",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="dailyrecord",
            name="clear_boom_count",
            field=models.PositiveIntegerField(default=0, verbose_name="炸清局数"),
        ),
        migrations.AlterField(
            model_name="dailyrecord",
            name="clear_in_count",
            field=models.PositiveIntegerField(default=0, verbose_name="接清局数"),
        ),
        migrations.AlterField(
            model_name="dailyrecord",
            name="comment",
            field=models.TextField(blank=True, verbose_name="当天评论"),
        ),
        migrations.AlterField(
            model_name="dailyrecord",
            name="opponent_name",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="对手名（可选）"
            ),
        ),
        migrations.AlterField(
            model_name="dailyrecord",
            name="score",
            field=models.IntegerField(default=0, verbose_name="得分/积分"),
        ),
        migrations.AlterField(
            model_name="dailyrecord",
            name="score_against",
            field=models.PositiveIntegerField(default=0, verbose_name="对方得分"),
        ),
        migrations.AlterField(
            model_name="dailyrecord",
            name="score_for",
            field=models.PositiveIntegerField(default=0, verbose_name="我方得分"),
        ),
    ]
