# Generated by Django 6.0.3 on 2026-03-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0004_remove_dailyrecord_clear_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyrecord",
            name="big_jin",
            field=models.PositiveIntegerField(default=0, verbose_name="大金数"),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="foul_count",
            field=models.PositiveIntegerField(default=0, verbose_name="犯规数"),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="golden_nine",
            field=models.PositiveIntegerField(default=0, verbose_name="黄金九数"),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="small_jin",
            field=models.PositiveIntegerField(default=0, verbose_name="小金数"),
        ),
    ]
