# Generated by Django 6.0.3 on 2026-03-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0005_dailyrecord_big_jin_dailyrecord_foul_count_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dailyrecord",
            name="unique_daily_record_per_user_per_date",
        ),
    ]
