# Generated by Django 6.0.3 on 2026-05-09 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0008_moment_momentcomment_momentlike_momentmedia_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BattleRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("battle_time", models.DateTimeField(verbose_name="约战时间")),
                ("location", models.CharField(max_length=120, verbose_name="地点")),
                (
                    "player_count",
                    models.PositiveIntegerField(default=1, verbose_name="寻找人数"),
                ),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["battle_time", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BattleResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="battlerequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="battle_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="battleresponse",
            name="battle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="diary.battlerequest",
            ),
        ),
        migrations.AddField(
            model_name="battleresponse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="battle_responses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="battleresponse",
            constraint=models.UniqueConstraint(
                fields=("battle", "user"), name="unique_battle_response"
            ),
        ),
    ]
